package drift

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestHashSpec(t *testing.T) {
	tmpDir := t.TempDir()
	specPath := filepath.Join(tmpDir, "spec.yaml")
	content := "key: value\nnested:\n  field: test\n"

	if err := os.WriteFile(specPath, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	hash, err := HashSpec(specPath)
	if err != nil {
		t.Fatalf("HashSpec() error = %v", err)
	}

	if len(hash) != 16 {
		t.Errorf("expected 16 char hash, got %d: %s", len(hash), hash)
	}

	hash2, _ := HashSpec(specPath)
	if hash != hash2 {
		t.Error("hash should be deterministic")
	}
}

func TestHashSpecNonExistent(t *testing.T) {
	_, err := HashSpec("/nonexistent/path")
	if err == nil {
		t.Error("expected error for non-existent spec file")
	}
}

func TestHashSpecContent(t *testing.T) {
	h1 := HashSpecContent("hello")
	h2 := HashSpecContent("hello")
	h3 := HashSpecContent("world")

	if h1 != h2 {
		t.Error("hash should be deterministic")
	}
	if h1 == h3 {
		t.Error("different content should produce different hashes")
	}
}

func TestDetectDrift(t *testing.T) {
	tmpDir := t.TempDir()
	specPath := filepath.Join(tmpDir, "spec.yaml")
	initialContent := "version: 1\nendpoints:\n  - /users\n  - /posts\n"

	if err := os.WriteFile(specPath, []byte(initialContent), 0644); err != nil {
		t.Fatal(err)
	}

	specHash, _ := HashSpec(specPath)

	report, err := DetectDrift("src/api/handlers.go", "BLUE-204", specPath, specHash, "agent:blue")
	if err != nil {
		t.Fatalf("DetectDrift() error = %v", err)
	}

	if report.DriftDetected {
		t.Error("expected no drift when spec hasn't changed")
	}
	if report.Severity != SeverityNone {
		t.Errorf("expected severity none, got %v", report.Severity)
	}
	if report.Spec != "BLUE-204" {
		t.Errorf("expected spec BLUE-204, got %q", report.Spec)
	}
	if report.GeneratedBy != "agent:blue" {
		t.Errorf("expected generated by agent:blue, got %q", report.GeneratedBy)
	}
}

func TestDetectDriftWithChange(t *testing.T) {
	tmpDir := t.TempDir()
	specPath := filepath.Join(tmpDir, "spec.yaml")
	if err := os.WriteFile(specPath, []byte("original content"), 0644); err != nil {
		t.Fatal(err)
	}

	specHash, _ := HashSpec(specPath)

	if err := os.WriteFile(specPath, []byte("modified content with new endpoints and features"), 0644); err != nil {
		t.Fatal(err)
	}

	report, err := DetectDrift("src/api/handlers.go", "BLUE-204", specPath, specHash, "agent:blue")
	if err != nil {
		t.Fatalf("DetectDrift() error = %v", err)
	}

	if !report.DriftDetected {
		t.Error("expected drift detected when spec changed")
	}
	if report.Severity != SeverityHigh {
		t.Errorf("expected severity high, got %v", report.Severity)
	}
	if report.CurrentSpecHash == "" {
		t.Error("expected current spec hash to be set")
	}
	if report.SpecHashAtGen != specHash {
		t.Errorf("expected spec hash at gen %q, got %q", specHash, report.SpecHashAtGen)
	}
}

func TestDetectDriftNoSpecPath(t *testing.T) {
	report, err := DetectDrift("src/file.go", "BLUE-1", "", "abc123", "human")
	if err != nil {
		t.Fatalf("DetectDrift() error = %v", err)
	}
	if report.DriftDetected {
		t.Error("expected no drift when no spec path provided")
	}
	if report.Recommendation == "" {
		t.Error("expected recommendation message")
	}
}

func TestDetectDriftNoSpecHash(t *testing.T) {
	tmpDir := t.TempDir()
	specPath := filepath.Join(tmpDir, "spec.yaml")
	os.WriteFile(specPath, []byte("content"), 0644)

	report, err := DetectDrift("src/file.go", "BLUE-1", specPath, "", "human")
	if err != nil {
		t.Fatalf("DetectDrift() error = %v", err)
	}
	if report.DriftDetected {
		t.Error("expected no drift when no original hash")
	}
}

func TestDetectDriftNoSpecPathOrHash(t *testing.T) {
	report, err := DetectDrift("src/file.go", "BLUE-1", "", "", "human")
	if err != nil {
		t.Fatalf("DetectDrift() error = %v", err)
	}
	if report.DriftDetected {
		t.Error("expected no drift")
	}
}

func TestReportString(t *testing.T) {
	r := &Report{
		File:          "src/auth/tenant.ts",
		Spec:          "BLUE-204",
		GeneratedAt:   "2026-03-14T00:00:00Z",
		GeneratedBy:   "agent:blue",
		SpecHashAtGen: "abc123f",
		CurrentSpecHash: "def456a",
		DriftDetected: true,
		Severity:      SeverityHigh,
		AffectedLines: 47,
		Recommendation: "DRIFT DETECTED — spec has changed since code generation",
	}

	s := r.String()
	if s == "" {
		t.Error("expected non-empty report string")
	}
	if !strings.Contains(s, "DRIFT DETECTED") {
		t.Error("expected drift detection message")
	}
}

func TestReportStringNoDrift(t *testing.T) {
	r := &Report{
		File:          "src/file.go",
		Spec:          "BLUE-1",
		GeneratedAt:   "2026-01-01T00:00:00Z",
		GeneratedBy:   "human",
		SpecHashAtGen: "abc",
		CurrentSpecHash: "abc",
		DriftDetected: false,
		Severity:      SeverityNone,
		Recommendation: "no drift detected — spec hash matches",
	}

	s := r.String()
	if s == "" {
		t.Error("expected non-empty report string")
	}
	if strings.Contains(s, "DRIFT DETECTED") {
		t.Error("should not show drift when none detected")
	}
}



func TestEstimateAffectedLines(t *testing.T) {
	tmpDir := t.TempDir()
	specPath := filepath.Join(tmpDir, "spec.yaml")
	content := "line1\nline2\nline3\nline4\nline5\n"
	os.WriteFile(specPath, []byte(content), 0644)

	report, err := DetectDrift("f.go", "S-1", specPath, "oldhash", "human")
	if err != nil {
		t.Fatal(err)
	}

	if report.AffectedLines <= 0 {
		t.Logf("affected lines: %d (may vary based on hash comparison)", report.AffectedLines)
	}
}
