package drift

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"unicode/utf8"
)

func TestHashSpec(t *testing.T) {
	tmpDir := t.TempDir()
	specPath := filepath.Join(tmpDir, "spec.yaml")
	content := "key: value\nnested:\n  field: test\n"

	if err := os.WriteFile(specPath, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	hash, err := HashSpec(specPath)
	if err != nil {
		t.Fatalf("HashSpec() error = %v", err)
	}

	if len(hash) != 16 {
		t.Errorf("expected 16 char hash, got %d: %s", len(hash), hash)
	}

	hash2, _ := HashSpec(specPath)
	if hash != hash2 {
		t.Error("hash should be deterministic")
	}
}

func TestHashSpecNonExistent(t *testing.T) {
	_, err := HashSpec("/nonexistent/path")
	if err == nil {
		t.Error("expected error for non-existent spec file")
	}
}

func TestHashSpecContent(t *testing.T) {
	h1 := HashSpecContent("hello")
	h2 := HashSpecContent("hello")
	h3 := HashSpecContent("world")

	if h1 != h2 {
		t.Error("hash should be deterministic")
	}
	if h1 == h3 {
		t.Error("different content should produce different hashes")
	}
	if len(h1) != 16 {
		t.Errorf("expected 16 char hash, got %d: %s", len(h1), h1)
	}
}

func TestDetectDrift(t *testing.T) {
	tmpDir := t.TempDir()
	specPath := filepath.Join(tmpDir, "spec.yaml")
	initialContent := "version: 1\nendpoints:\n  - /users\n  - /posts\n"

	if err := os.WriteFile(specPath, []byte(initialContent), 0644); err != nil {
		t.Fatal(err)
	}

	specHash, _ := HashSpec(specPath)

	report, err := DetectDrift("src/api/handlers.go", "BLUE-204", specPath, specHash, "agent:blue")
	if err != nil {
		t.Fatalf("DetectDrift() error = %v", err)
	}

	if report.DriftDetected {
		t.Error("expected no drift when spec hasn't changed")
	}
	if report.Severity != SeverityNone {
		t.Errorf("expected severity none, got %v", report.Severity)
	}
	if report.Spec != "BLUE-204" {
		t.Errorf("expected spec BLUE-204, got %q", report.Spec)
	}
	if report.GeneratedBy != "agent:blue" {
		t.Errorf("expected generated by agent:blue, got %q", report.GeneratedBy)
	}
	if report.File != "src/api/handlers.go" {
		t.Errorf("expected file src/api/handlers.go, got %q", report.File)
	}
	if report.Recommendation == "" {
		t.Error("expected recommendation message")
	}
}

func TestDetectDriftWithChange(t *testing.T) {
	tmpDir := t.TempDir()
	specPath := filepath.Join(tmpDir, "spec.yaml")
	if err := os.WriteFile(specPath, []byte("original content"), 0644); err != nil {
		t.Fatal(err)
	}

	specHash, _ := HashSpec(specPath)

	if err := os.WriteFile(specPath, []byte("modified content\nwith new endpoints\nand features\n"), 0644); err != nil {
		t.Fatal(err)
	}

	report, err := DetectDrift("src/api/handlers.go", "BLUE-204", specPath, specHash, "agent:blue")
	if err != nil {
		t.Fatalf("DetectDrift() error = %v", err)
	}

	if !report.DriftDetected {
		t.Error("expected drift detected when spec changed")
	}
	if report.Severity != SeverityHigh {
		t.Errorf("expected severity high, got %v", report.Severity)
	}
	if report.CurrentSpecHash == "" {
		t.Error("expected current spec hash to be set")
	}
	if report.SpecHashAtGen != specHash {
		t.Errorf("expected spec hash at gen %q, got %q", specHash, report.SpecHashAtGen)
	}
	if report.Recommendation == "" {
		t.Error("expected recommendation message")
	}
	if report.AffectedLines <= 0 {
		t.Errorf("expected affected lines > 0, got %d", report.AffectedLines)
	}
}

func TestDetectDriftNoSpecPath(t *testing.T) {
	report, err := DetectDrift("src/file.go", "BLUE-1", "", "abc123", "human")
	if err != nil {
		t.Fatalf("DetectDrift() error = %v", err)
	}
	if report.DriftDetected {
		t.Error("expected no drift when no spec path provided")
	}
	if report.Recommendation == "" {
		t.Error("expected recommendation message")
	}
	if report.Severity != SeverityNone {
		t.Errorf("expected severity none, got %v", report.Severity)
	}
}

func TestDetectDriftNoSpecHash(t *testing.T) {
	tmpDir := t.TempDir()
	specPath := filepath.Join(tmpDir, "spec.yaml")
	os.WriteFile(specPath, []byte("content"), 0644)

	report, err := DetectDrift("src/file.go", "BLUE-1", specPath, "", "human")
	if err != nil {
		t.Fatalf("DetectDrift() error = %v", err)
	}
	if report.DriftDetected {
		t.Error("expected no drift when no original hash")
	}
	if report.Recommendation == "" {
		t.Error("expected recommendation message")
	}
	if report.Severity != SeverityNone {
		t.Errorf("expected severity none, got %v", report.Severity)
	}
}

func TestDetectDriftNoSpecPathOrHash(t *testing.T) {
	report, err := DetectDrift("src/file.go", "BLUE-1", "", "", "human")
	if err != nil {
		t.Fatalf("DetectDrift() error = %v", err)
	}
	if report.DriftDetected {
		t.Error("expected no drift")
	}
}

func TestReportString(t *testing.T) {
	r := &Report{
		File:            "src/auth/tenant.ts",
		Spec:            "BLUE-204",
		GeneratedAt:     "2026-03-14T00:00:00Z",
		GeneratedBy:     "agent:blue",
		SpecHashAtGen:   "abc123f",
		CurrentSpecHash: "def456a",
		DriftDetected:   true,
		Severity:        SeverityHigh,
		AffectedLines:   47,
		Recommendation:  "DRIFT DETECTED — spec has changed since code generation",
	}

	s := r.String()
	if s == "" {
		t.Error("expected non-empty report string")
	}
	if !strings.HasPrefix(s, "  gitwhy drift report\n  ") {
		t.Error("expected report to start with header followed by separator")
	}

	if c := strings.Count(s, "DRIFT DETECTED — spec has changed since code generation"); c < 2 {
		t.Errorf("expected at least 2 occurrences of drift message, got %d", c)
	}
	if !strings.Contains(s, "DRIFT DETECTED") {
		t.Error("expected drift detection message")
	}

	lines := strings.Split(s, "\n")
	if len(lines) > 1 && utf8.RuneCountInString(strings.TrimSpace(lines[1])) != 50 {
		t.Error("expected exactly 50 dashes in separator line")
	}

	if !strings.Contains(s, "─────") {
		t.Error("expected dashes separator")
	}
	if !strings.Contains(s, "file:") {
		t.Error("expected file field")
	}
	if !strings.Contains(s, "spec:") {
		t.Error("expected spec field")
	}
	if !strings.Contains(s, "generated:") {
		t.Error("expected generated field")
	}
	if !strings.Contains(s, "2026-03-14") {
		t.Error("expected generation date in output")
	}
	if strings.Contains(s, "2026-03-14T") {
		t.Error("expected date without T separator in output")
	}
	if !strings.Contains(s, "2026-03-14  by agent:blue") {
		t.Error("expected date without T separator next to 'by' field")
	}
	if !strings.Contains(s, "spec hash:") {
		t.Error("expected spec hash field")
	}
	if !strings.Contains(s, "abc123f") {
		t.Error("expected SpecHashAtGen hash in output")
	}
	if !strings.Contains(s, "def456a") {
		t.Error("expected CurrentSpecHash hash in output")
	}
	if !strings.Contains(s, "\n\n  DRIFT DETECTED") {
		t.Error("expected blank line before drift section")
	}
	if !strings.Contains(s, "Lines affected:") {
		t.Error("expected Lines affected field")
	}
	if !strings.Contains(s, "+47") {
		t.Error("expected affected line count in output")
	}
}

func TestReportStringNoDrift(t *testing.T) {
	r := &Report{
		File:           "src/file.go",
		Spec:           "BLUE-1",
		GeneratedAt:    "2026-01-01T00:00:00Z",
		GeneratedBy:    "human",
		SpecHashAtGen:  "abc",
		CurrentSpecHash: "abc",
		DriftDetected:  false,
		Severity:       SeverityNone,
		Recommendation: "no drift detected — spec hash matches",
	}

	s := r.String()
	if s == "" {
		t.Error("expected non-empty report string")
	}
	if !strings.HasPrefix(s, "  gitwhy drift report\n  ") {
		t.Error("expected report to start with header followed by separator")
	}
	if !strings.Contains(s, r.Recommendation) {
		t.Error("expected recommendation in output")
	}
	if strings.Contains(s, "DRIFT DETECTED") {
		t.Error("should not show drift when none detected")
	}
}

func TestReportStringDriftWithLines(t *testing.T) {
	r := &Report{
		File:            "src/file.go",
		Spec:            "BLUE-1",
		GeneratedAt:     "2026-01-01T00:00:00Z",
		GeneratedBy:     "agent:blue",
		SpecHashAtGen:   "abc",
		CurrentSpecHash: "def",
		DriftDetected:   true,
		Severity:        SeverityHigh,
		AffectedLines:   10,
		Recommendation:  "DRIFT DETECTED",
	}

	s := r.String()
	if !strings.Contains(s, "Lines affected") {
		t.Error("expected Lines affected section")
	}
}

func TestReportStringDriftZeroLines(t *testing.T) {
	r := &Report{
		File:            "src/file.go",
		Spec:            "BLUE-1",
		GeneratedAt:     "2026-01-01T00:00:00Z",
		GeneratedBy:     "agent:blue",
		SpecHashAtGen:   "abc",
		CurrentSpecHash: "def",
		DriftDetected:   true,
		Severity:        SeverityHigh,
		AffectedLines:   0,
		Recommendation:  "DRIFT DETECTED",
	}

	s := r.String()
	if strings.Contains(s, "Lines affected") {
		t.Error("expected no Lines affected for 0 affected lines")
	}
}

func TestReportStringDriftOneLine(t *testing.T) {
	r := &Report{
		File:            "src/file.go",
		Spec:            "BLUE-1",
		GeneratedAt:     "2026-01-01T00:00:00Z",
		GeneratedBy:     "agent:blue",
		SpecHashAtGen:   "abc",
		CurrentSpecHash: "def",
		DriftDetected:   true,
		Severity:        SeverityHigh,
		AffectedLines:   1,
		Recommendation:  "DRIFT DETECTED",
	}

	s := r.String()
	if !strings.Contains(s, "Lines affected") {
		t.Error("expected Lines affected for 1 affected line")
	}
}

func TestEstimateAffectedLines(t *testing.T) {
	tmpDir := t.TempDir()
	specPath := filepath.Join(tmpDir, "spec.yaml")
	content := "line1\nline2\nline3\nline4\nline5\n"
	os.WriteFile(specPath, []byte(content), 0644)

	lines := estimateAffectedLines(specPath)
	if lines != 5 {
		t.Errorf("expected 5 affected lines, got %d", lines)
	}
}

func TestDashes(t *testing.T) {
	result := dashes(5)
	if result != "─────" {
		t.Errorf("expected 5 dashes, got %q", result)
	}

	result = dashes(0)
	if result != "" {
		t.Errorf("expected empty string for 0 dashes, got %q", result)
	}

	result = dashes(50)
	if utf8.RuneCountInString(result) != 50 {
		t.Errorf("expected 50 dashes, got %d runes", utf8.RuneCountInString(result))
	}

	result = dashes(49)
	if utf8.RuneCountInString(result) != 49 {
		t.Errorf("expected 49 dashes, got %d runes", utf8.RuneCountInString(result))
	}
}

func TestSeverityValues(t *testing.T) {
	if SeverityNone != "none" {
		t.Errorf("unexpected SeverityNone: %q", SeverityNone)
	}
	if SeverityLow != "low" {
		t.Errorf("unexpected SeverityLow: %q", SeverityLow)
	}
	if SeverityMedium != "medium" {
		t.Errorf("unexpected SeverityMedium: %q", SeverityMedium)
	}
	if SeverityHigh != "high" {
		t.Errorf("unexpected SeverityHigh: %q", SeverityHigh)
	}
}

func TestDetectDriftSeverityNone(t *testing.T) {
	tmpDir := t.TempDir()
	specPath := filepath.Join(tmpDir, "spec.yaml")
	os.WriteFile(specPath, []byte("content"), 0644)
	specHash, _ := HashSpec(specPath)

	report, err := DetectDrift("f.go", "S-1", specPath, specHash, "human")
	if err != nil {
		t.Fatal(err)
	}
	if report.Severity != SeverityNone {
		t.Errorf("expected severity none, got %v", report.Severity)
	}
	if report.DriftDetected {
		t.Error("expected no drift")
	}
}

func TestDetectDriftHashSpecError(t *testing.T) {
	_, err := DetectDrift("f.go", "S-1", "/nonexistent/spec", "somehash", "human")
	if err == nil {
		t.Error("expected error when spec file doesn't exist")
	}
}

func TestGeneratedAtFormat(t *testing.T) {
	report, err := DetectDrift("f.go", "S-1", "", "", "human")
	if err != nil {
		t.Fatal(err)
	}
	if report.GeneratedAt == "" {
		t.Error("expected GeneratedAt to be set")
	}
}

func TestCurrentSpecHashNotSet(t *testing.T) {
	report, err := DetectDrift("f.go", "S-1", "", "", "human")
	if err != nil {
		t.Fatal(err)
	}
	if report.CurrentSpecHash != "" {
		t.Errorf("expected empty CurrentSpecHash, got %q", report.CurrentSpecHash)
	}
}

func TestEstimateAffectedLinesFileNotFound(t *testing.T) {
	lines := estimateAffectedLines("/nonexistent/path/spec.yaml")
	if lines != 0 {
		t.Errorf("expected 0 for nonexistent file, got %d", lines)
	}
}

func TestEstimateAffectedLinesEmptyFile(t *testing.T) {
	tmpDir := t.TempDir()
	specPath := filepath.Join(tmpDir, "empty.yaml")
	os.WriteFile(specPath, []byte(""), 0644)

	lines := estimateAffectedLines(specPath)
	if lines != 0 {
		t.Errorf("expected 0 for empty file, got %d", lines)
	}
}
